### ISSUE TITLE
client credentials

### ISSUE THREAD

**Issue by whitneyland** [s-KaiNet/sp-request#10]
sp-request supports this form of authentication using an AAD app:
```
    var credentialOptions = {
    		clientId: clientId,
		clientSecret: clientSecret
    }
    let spr = sprequest.create(credentialOptions)
```

Can this same method be used with user credentials, to support the scenario described here in this Microsoft blog post?
https://blogs.msdn.microsoft.com/kaevans/2014/04/15/calling-o365-apis-from-your-web-api-on-behalf-of-a-user/

I'm willing to keep digging, any input appreciated.

**Comment by s-KaiNet** [comment]
Actually `sp-request` is intended to work with SharePoint, thus use SharePoint app registered via SharePoint interface. In a nutshell it's an AAD app, but it doesn't showed up in AAD apps interface and behaves different. Client credentials flow for SharePoint app also uses different token url (it uses Azure ACS). And it doesn't support on-behalf flow described in the blog. So `sp-request` most definitely won't help you.    

Now to your issue. As far as I understand, you have an app, which performs AAD authentication and obtains user access token. You want this token to be passed to SharePoint API on behalf-of. There is a special library to work with AAD from node.js - [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs). It contains various methods of acquiring an access token. Unfortunately, current version doesn't support flow described in a blog post (acquire token on behalf of), but I found a PR to `adal-node`, which implements on behalf-of functionality - [here is the link](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/159). I'm pretty sure you can reuse it for your specific need.

**Comment by s-KaiNet** [comment]
Hmmm... now when thinking about your question once again it seems I understand what you are asking for :)  
Your app contains access token and you want `sp-request` to generate new access token on behalf? That's a good question indeed. I need to check if it's possible with Azure ACS endpoint.

**Comment by s-KaiNet** [comment]
Closing... feel free to reopen
