### ISSUE TITLE
Get list Items, CAML query

### ISSUE THREAD

**Issue by DDAGitHub** [s-KaiNet/sp-request#11]
Hello!
I will be grateful if you explain me how I can get list Items with CAML query.
I can execute simple REST queries (request.get), but now I need to filter items by  the CAML query.
It's because I need to filter items  by 'contains' filter to the field of type Note (multi line field).
And can I understand, it's possible only through CAML query in the options of  request.post?  request.get?

With best regards,
Dmitry

**Comment by s-KaiNet** [comment]
Hi Dmitry, 

You can use below query:
> _api/web/lists/GetByTitle('MyList')/items?$filter=substringof('word',Title)  

BTW consider [PnP-JS-Core](https://github.com/SharePoint/PnP-JS-Core) library for making REST queries to SharePoint. The library has fluent interface for interacting with SharePoint. You can use it with node.js with help of [node-pnp-js](https://github.com/s-KaiNet/node-pnp-js)  
For example your code with PnP-JS-Core will be:   
```javascript
import pnp from "pnp";

pnp.sp.web.lists.getByTitle('TestList').items.filter('substringof(\'item\',Title)').get().then(result => {
	console.log(result);
});
```  
Much more convenient and less code.

**Comment by DDAGitHub** [comment]
Hi Sergei.
I have tried this way **filter=substringof('word',Title)**.
The problem is that it does not work for the field of type **Note** (multi line text).
I think there is way like as you answered here [https://sharepoint.stackexchange.com/questions/199000/rest-to-create-a-sharepoint-list-in-node-js-hosted-offsite](url).
But I dont  understand how to do it, I do not have enough experience.

Thank you for the  link to PnP-JS-Core, I'll try it.

**Comment by s-KaiNet** [comment]
In that case you can try to use rest api only. Your caml query:
```xml
<View>
    <Query>
        <Where>
            <Contains>
                <FieldRef Name='MultCol'/>
                <Value Type='Text'>cool</Value>
            </Contains>
        </Where>
    </Query>
</View>
```   
with PnP-JS-Core your request will be:  
```javascript
pnp.sp.web.lists.getByTitle("Test list").getItemsByCAMLQuery({
	ViewXml: "<View><Query><Where><Contains><FieldRef Name='MultCol'/><Value Type='Text'>cool</Value></Contains></Where></Query></View>"
}).then(result => {
	console.log(result);
});
```  
with pure rest api it will be:  
```
POST /_api/web/Lists/GetByTitle('Test list')/GetItems HTTP/1.1
Accept: application/json;odata=verbose
X-RequestDigest: 0x3E2CC492485E408481084...D3D55BAF7FD5674B26BA,07 Oct 2017 15:10:03 -0000
Content-Type: application/json;odata=verbose
{
	"query": {
		"__metadata": {
			"type": "SP.CamlQuery"
		},
		"ViewXml": "<View><Query><Where><Contains><FieldRef Name='MultCol'/><Value Type='Text'>cool</Value></Contains></Where></Query></View>"
	}
}
```

**Comment by DDAGitHub** [comment]
Hi Sergei, sorry for probably elementaryc questions.
I can't understand what is wrong.

This code works:
<pre><code>
 var  pnp=require('sp-pnp-js');
  var  NodeFetchClient=require('node-pnp-js');

  pnp.setup({
    sp: {
      fetchClientFactory: function () {
          return new NodeFetchClient.default({ username: "***", password: "***" });
      }
    }
  });

  new pnp.Web("URL").get()
      .then(data => {
            console.log(`Your web title: ${data.Title}`);
  })
</code></pre>

but adding this from documentation :
<pre>
  // from https://github.com/SharePoint/PnP-JS-Core/wiki/Basic--Operations
  pnp.sp.web.lists.getByTitle("Документы").get().then(r => {
     console.log(r);
  });
</pre>
I get the error
> (node:3728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'indexOf' of null
> (node:3728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by s-KaiNet** [comment]
Consider different setup options for `node-pnp-js` - [this one](https://github.com/s-KaiNet/node-pnp-js#1-use-web-or-site-constructor-like-in-a-sample-above-with-siteurl-constructor-param) and [this another one](https://github.com/s-KaiNet/node-pnp-js#2-use-baseurl-configuration-parameter-coming-from-sp-pnp-js)    
To make your last code work, you need to use Web constructor, because `pnp-js-core` doesn't know your web url:    
```javascript
new pnp.Web("URL").lists.getByTitle("Документы").get().then(r => {
     console.log(r);
  });
```  
OR another way to do that:   

you can setup it differently ([like this](https://github.com/s-KaiNet/node-pnp-js#2-use-baseurl-configuration-parameter-coming-from-sp-pnp-js)):    
```javascript
pnp.setup({
    sp: {
      fetchClientFactory: function () {
          return new NodeFetchClient.default({ username: "***", password: "***" });
      },
      baseUrl: "URL" // assuming URL is your sharepoint site url
    }
  });
````  
now you can use sample from pnp-js wiki without issues, because pnp-js knows your site url and `pnp.sp.web` references your site:   
```javascript
pnp.sp.web.lists.getByTitle("Документы").get().then(r => {
     console.log(r);
  });
```

**Comment by DDAGitHub** [comment]
Thank you, Sergei.
I saw these links and I tried to include baseUrl in the pnp.setup.
But there were no result...
After hours of research it turned out in our site **getByTitle**  does not work.
Probably, this is due to the fact that our site has variants (somewhere I saw discussion about getItemsByCAMLQuery in a site with variations).
I use lists.getById() and now all works.

Many thanks again!

**Comment by s-KaiNet** [comment]
BTW you can also use `sp.web.getList("sites/yoursite/Lists/YourList")`

**Comment by DDAGitHub** [comment]
Thank you, this more convenient than by ID.
