### ISSUE TITLE
How to get file content wit sp request,

### ISSUE THREAD

**Issue by sanjeev2315** [s-KaiNet/sp-request#16]
Hi,

I have tried using both sp-request and sp-download but i could not get actual sharepoint file data in binary. 
1. Problem with sp-download is , it downloads the file to disk directly but i can not afford that as it is performance issue for me, i need file binary stream, not sure how to do that.

2. With sp-request, i tries using getfilebyserverrelativeurl(url)$value but it is giving me a whole big xml/xsd(lot of metadata) kind of structure but not binary content, is there any way that i get binary .doc file content with any of these libraries, I have spent lot of time but could not figure out how to do that.

**Comment by s-KaiNet** [comment]
Hi, 

Please checkout [this method](https://github.com/koltyakov/sppull/blob/master/src/api/index.ts#L280) from sppull library. I guess that's something you're looking for.

**Comment by saurabh-lodha-16** [comment]
@sanjeev2315 were you able to solve the issue ? I want to do a similar functionality in my application. If possible can you please share the working method. Thanks.

**Comment by sanjeev2315** [comment]
yes, I written the method which @s-KaiNet mentioned

**Comment by sanjeev2315** [comment]
> @sanjeev2315 were you able to solve the issue ? I want to do a similar functionality in my application. If possible can you please share the working method. Thanks.

Yes, I written the same kind of function which @s-KaiNet  mentioned

**Comment by s-KaiNet** [comment]
Glad you guys resolved the issue. I'm closing it, please feel free to reopen.

**Comment by MDangleben** [comment]
How was this resolved using sp-request? Is got.stream exposed anywhere?
