### ISSUE TITLE
Batch queries support (question)

### ISSUE THREAD

**Issue by koltyakov** [s-KaiNet/sp-request#2]
Hi Sergei,

First of all, thank you for this great library, it found a place in our projects and do its job nicely!

Question: Do you have a clue, how to add batch queries support to `sp-request` library?
To be able to combine the reasonable set of REST queries to one single batch and then send a network request all at once (for SPO and SP2016, not SP2013 for sure, as REST $batch API is absent in SP2013). 
With some sort of syntax:

``` javascript
...
var spr = require("sp-request").create(ctx, env);
var batch = spr.createBatch();
var batchResults = [];
spr.getInBatch(restUrl1, batch).then(...);
spr.getInBatch(restUrl2, batch).then(...);
spr.postInBatch(restUrl2, batch, {
   body: { ... },
   headers: { ... }
}).then(...);
...
batch.execute().then(function() {
  console.log("All is done!", batchResults);
});
```

**Comment by s-KaiNet** [comment]
Hi Andrew, thank you very much!

For your question I think you can use promise.all (bluebird) or something
similar, since all requests in the module are promise-aware.

**Comment by koltyakov** [comment]
It's not about getting event then all responses are returned, but merging requests in one physical call, which can improve performance in some scenarios, especially in SPO.

Thanks for idea of Bluebird's promise.all this will be definitely cool for SP2013 communication logic.

**Comment by s-KaiNet** [comment]
Now I see... you are about $batch support in odata. I'd rather say I don't
have plans to include that, because the main purpose of this library is to
provide authentication and that's it. For example in request module you
don't have an option to construct batch, so sp-request also doesn't support
this. You need to implement it on your own.

**Comment by koltyakov** [comment]
Ok, got it. Thank you for the info.
